### ISSUE TITLE
[Enhancement] CPU/GPU Freq Governor at sysmodule level

### ISSUE THREAD

**Issue by KazushiMe** [KazushiMe/Switch-OC-Suite#2]
## Requirements
- [x] Sampling should have low pressure on CPU
    - PoC: based on `svcGetInfo(InfoType_IdleTickCount)` and `nvIoctl(NVGPU_GPU_IOCTL_PMU_GET_GPU_LOAD)`
        - Sampling utilization @ 60Hz for all 4 CPU cores and GPU takes up about 3% on Core#3 @ 612 MHz
        - The impact on performance or power consumption could be considered negligible
        - Further optimization is achievable (dynamic sampling rate, etc.)
- [x] Frequencies could be set very fast
    - 10000 consecutive `Clocks::SetHz(CPU, 612MHz);Clocks::SetHz(CPU, 1020MHz);` takes ~4300 ms
    - i.e. ~13 ms if CPU clock is set 60 times in one sec.
- [x] Quick and adaptive algorithm
    - Acts like the "ondemand" or "conservative" governor in Linux kernel
    - Multiple levels of bias towards performance or battery-saving according to power state
- [ ] Lower power consumption, or the implementation would be pointless
    - ~~CPU@>1020MHz and GPU@>768MHz consumes significantly more power even at low usage% (e.g. Home Screen / Game Menus).~~
## Todo list
- ~~Integrate ReverseNX-RT overlay~~
    - Ban risks exist if users have no knowledge of what they are doing
- [x] Rewrite `ClockManager::`
- [ ] Implement custom configurations in a similar way to what [jope82](https://github.com/jope82/sys-clk-uncapped-gpu-and-other-extras/tree/develop) has done
- [ ] Rewrite `Governor::`
    - Replace hard-coded coefficients with auto-generated ones
    - User configurable upper(target)/lower frequency bounds, and a simple performance-power setting for every profile in each title
- [ ] Full Overlay & manager support
    - Performance-power slider (global and title-based) like the one in Windows 10

| Performance-Power Setting | Overclock                                         | Governor Mode | Governor Availability |
| :----------------- | :------------------------------------------------ | :-------------------- | ------------------ |
| Best Performance   | Target frequency or 1963/1267 by default | Disabled              | Level 0: Not available |
| Better Performance | Target frequency or 1785/921 by default | Ondemand: bump to max if usage% is above threshold, or slightly drop down | Level 1: Enable when OC frequencies are above 1020/768 |
| Customize    | Target frequency if exists                      | Default: Balance | Default: Level 2 |
| Better Powersave     | Target frequency if exists            | Balance: maintain usage% in the acceptable range, already implemented in PoC | Level 2: Enable when GPU frequency > 460 |
| Best Powersave      | Target frequency (must be lower than what the game officially requested) or disable by default | Powersave: stay as low as possible | Level 3: Enable when GPU frequency > 153 |

**Comment by lsp199308** [comment]
、等等、等等等大佬

**Comment by KazushiMe** [comment]
[Governor_PoC](https://github.com/KazushiMe/Switch-OC-Suite/tree/Governor_PoC) branch has been pushed.

[Governor_PoC@1bb6773.zip](https://github.com/KazushiMe/Switch-OC-Suite/files/7212993/Governor_PoC%401bb6773.zip)

Usage: use Sysmodules Tesla Overlay to enable/disable it. Sys-clk overlay/manager/user-customized profiles won't work for now.

Need to check if Governor_PoC branch could prolong battery life.

CPUFreq MHz | CPULoad (Handheld) % | CPULoad (Dock) % | GPUFreq MHz | 0x00020000/ 0x00020002 (230.4) | 0x00020001/ 0x00020003/ 0x00020005 (307.2) | 0x00010000/ 0x00020004/ 0x00020006 (384) | 0x92220007/ 0x92220008 (460.8) | 0x00010001/ 0x00010002 (768)(Dock)
:-- | --: | --: | :-- | --: | --: | --: | --: | --:
612 | 20 | 20 | 76.8 | 30 | 25 | 20 | 20 | 5
714 | 50 | 40 | 153.6 | 50 | 35 | 40 | 30 | 10
816 | 60 | 50 | 230.4 | 85 | 55 | 50 | 40 | 20
918 | 70 | 60 | 307.2 | 100 | 85 | 70 | 50 | x
1020 | 80 | 70 | 384 | x | 100 | 85 | 70 | 30
1122 | 90 | 80 | 460.8 | x | x | 100 | 85 | 40
1224 | 95 | 90 | 537.6 | x | x | x | 100 | 50
1326 | x | x | 614.4 | x | x | x | x | x
1428 | x | x | 691.2 | x | x | x | x | 60
1581 | x | x | 768 | x | x | x | x | 70
1683 | x | x | 844.8 | x | x | x | x | x
1785 | 100 | 95 | 921.6 | x | x | x | x | 80
1887 | x | x | 998.4 | x | x | x | x | x
1963.5 | x | x | 1075.2 | x | x | x | x | 90
2091 | x | x | 1152 | x | x | x | x | x
2193 | x | x | 1228.8 | x | x | x | x | x
2295 | x | 100 | 1267.2 | x | x | x | x | 100
2397 | x | x |   |   |   |   |   |  

Notes:
- Sample rate = 60Hz
- `CPULoadAvg = 0.4*CPU[0] + 0.3*CPU[1] + 0.3*CPU[2]`
- `CPULoadMax = MAX{CPU[0], CPU[1], CPU[2], CPU[3]}`
- `CPULoad = MAX{CPULoadAvg, CPULoadMax}`
- (tricky)`GPULoadAdjusted = GPULoad_PreviousSample * 0.4 + GPULoad_Now * 0.6`
- If CpuBoostMode is on, reset to stock(1963.5,76.8) until CpuBoostMode is off. (Check apm profile once per sec)

**Comment by MattyXarope** [comment]
Thanks for returning to this project, many of us in the community really appreciate it. 

I might add to this list of to do things is to compile the patch tools to use regular dll files instead of debug versions which are less common and more difficult to acquire.

**Comment by KazushiMe** [comment]
> Thanks for returning to this project, many of us in the community really appreciate it.
> 
> I might add to this list of to do things is to compile the patch tools to use regular dll files instead of debug versions which are less common and more difficult to acquire.

I'd recompiled and updated nx2elf for release in https://github.com/KazushiMe/Switch-OC-Suite/commit/8e119aaa95d8ad438a09ce24094c9846434c82ed, by courtesy of Github Actions.

**Comment by KazushiMe** [comment]
Reopen this as it might help reduce power consumption without affecting performance, at clock rates that are much higher than stock.

**Comment by Cooler3D** [comment]
@KazushiMe 
It would be great. With mixed, and especially low loads, dynamic frequency control can potentially reduce power consumption and heat dissipation - several times.

It's strange that console manufacturers always use a constant value. Even on portable consoles. If I'm not mistaken, Switch may become the first console in the world on which something like dynamic Governor can be started, even with the efforts of the great developer from community.

**Comment by Anxietytimmy** [comment]
Probably should also enable power saving mode at sometime like 5% battery

**Comment by Cooler3D** [comment]
> Probably should also enable power saving mode at sometime like 5% battery

Doesn't the default console have such a feature?

**Comment by Anxietytimmy** [comment]
> > Probably should also enable power saving mode at sometime like 5% battery
> 
> Doesn't the default console have such a feature?

nope

**Comment by KazushiMe** [comment]
Battery power draw monitor is implemented in overlay.
At idle state (where freq governor most likely steps in and sets lower freqs), power draw increases significantly (>0.3W) only when CPU ≥ 1887 MHz and GPU ≥ 1152 MHz on Mariko (~1.8W idle @ stock clocks with lowest brightness). Anything below this threshold is handled somewhat properly by the OS and SoC. And frequency governor running outside the kernel has intrinsic run-time overhead.
This idea might benefit Erista consoles, but I don't have access to one or any intention to support Erista except for RAM OC.

**Comment by Cooler3D** [comment]
Thank you. I lost sight of the fact that only userspace is available to us on Mariko.
If you have time and desire to try to solve this problem on Erista, I and other members of the Russian community will be happy to test it.
